version: '3.3'
services:
    frontend:
        build: 
            context: .
            dockerfile: ./frontend/Dockerfile.production     
        ports:
            - 80:80
        networks:
            - internal_service

    mockserver:
      build: ./mockServer
      command: sh /code/run.sh
      volumes:
        - ./mockServer:/code
      ports:
        - 8000:8000
      networks:
        - internal_service
   

networks:
  internal_service:
    external: true
