version: '3.3'
services:
    postgres:
        image: postgres
        env_file:
            - ./.env.production
        networks:
            - internal_service
        ports:
            - 5432:5432

    frontend:
        # build: ./frontend/Dockerfile.production
        build: 
            context: .
            dockerfile: ./frontend/Dockerfile.production     
        ports:
            - 80:80
        networks:
            - internal_service

    backend:
        build: ./backend
        command: node server.js
        volumes:
            - ./backend:/usr/src/app
        ports:
            - 8080:8080
        networks:
            - internal_service

    mockserver:
      build: ./mockServer
      command: sh /code/run.sh
      volumes:
        - ./mockServer:/code
      ports:
        - 8000:8000
      networks:
        - internal_service
   

networks:
  internal_service:
    external: true
