version: '3.3'
services:
    postgres:
        image: postgres
        env_file:
            - ./.env.dev
        networks:
            - internal_service
        ports:
            - 5432:5432

    frontend:
        build: ./frontend
        environment:
        - REACT_APP_BACKEND_ENDPOINT=${REACT_APP_BACKEND_ENDPOINT}
        command: sh /code/run.sh
        volumes:
        - ./frontend:/code
        ports:
        - 80:3000
        networks:
        - internal_service

    backend:
        build: ./backend
        command: node server.js
        volumes:
        - ./backend:/usr/src/app
        ports:
        - 8080:8080
        networks:
        - internal_service

    mockserver:
      build: ./mockServer
      command: sh /code/run.sh
      volumes:
      - ./mockServer:/code
      ports:
      - 8000:8000
      networks:
      - internal_service


    

networks:
  internal_service:
    external: true
